display_name: po0-clash

icon: ./assets/images/icon.png

supported_mime_type:
  - x-scheme-handler/clash
  - x-scheme-handler/clashmeta
  - x-scheme-handler/po0clash

keywords:
  - po0-clash
  - Clash
  - ClashMeta
  - Proxy

generic_name: po0-clash

categories:
  - Network

startup_notify: true

include: []